name: n_sukumi_maker
description: "新しい Flutter プロジェクトです。"

# 以下の行は、このパッケージが誤って pub.dev に公開されるのを防ぎます。
# プライベートなパッケージにはこの設定が推奨されます。
publish_to: 'none' # pub.dev に公開したい場合はこの行を削除してください。

# 以下はアプリのバージョンとビルド番号を定義します。
# バージョン番号は 1.2.43 のようにドットで区切られた3つの数字で構成されます。
# 後ろに `+1` のようなビルド番号を追加できます。
# Flutter ビルド時に --build-name や --build-number を指定して上書きすることも可能です。
# Android では build-name は versionName、build-number は versionCode として使われます。
# iOS では build-name は CFBundleShortVersionString、build-number は CFBundleVersion に対応します。
# Windows では build-name はメジャー・マイナー・パッチのバージョン、
# build-number はビルドのサフィックスとして使われます。
version: 1.0.0+1

environment:
  sdk: ^3.7.2  # Dart SDK のバージョン指定

# このプロジェクトが必要とする他のパッケージ（依存関係）をここで指定します。
# 依存パッケージを最新版に自動アップグレードするには、
# `flutter pub upgrade --major-versions` を使います。
# 新しいバージョンが利用可能か確認するには、`flutter pub outdated` を使います。
dependencies:
  flutter:
    sdk: flutter

  flutter_colorpicker: ^1.0.3  # カラーピッカー用パッケージ

  # 以下は Cupertino Icons フォント（iOS風アイコン）を追加します。
  # CupertinoIcons クラスと一緒に使用できます。
  cupertino_icons: ^1.0.8

  sqflite: ^2.3.2      # ← SQLite を操作するため
  path_provider: ^2.1.2  # ← データベースの保存パス取得のため
  path: ^1.8.3         # ← パス結合用（joinなど）

dev_dependencies: # 開発時に必要なパッケージ
  flutter_test:
    sdk: flutter  # テストフレームワーク

  # 下記の flutter_lints パッケージには、推奨される Lint 設定が含まれています。
  # コーディングの品質を保つためのルールが有効になります。
  # 実際のルールの有効化・無効化はルートにある analysis_options.yaml で行います。
  flutter_lints: ^5.0.0

# Dart 用 pubspec.yaml の一般的な情報については以下を参照してください：
# https://dart.dev/tools/pub/pubspec

# 以下のセクションは Flutter に特有の設定です。
flutter:

  # この行により、Material アイコンフォントがアプリに含まれ、
  # MaterialIcons クラスでアイコンが使えるようになります。
  uses-material-design: true

  # 画像などのアセットを追加する場合は以下のように記述します：
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # 解像度ごとに異なる画像バリエーションを使用する方法については：
  # https://flutter.dev/to/resolution-aware-images

  # パッケージ依存からアセットを追加する方法については：
  # https://flutter.dev/to/asset-from-package

  # カスタムフォントを追加する場合は以下のように fonts セクションを使います。
  # family（フォント名）と fonts（ファイルパス）の指定が必要です。
  # 例：
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # パッケージ依存のフォント利用方法については：
  # https://flutter.dev/to/font-from-package
